import type { Metadata, Viewport } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import { BRAND } from "@/lib/data";

import SmoothScrollProvider from "@/components/providers/SmoothScrollProvider";
import PersonalizationProvider from "@/components/providers/PersonalizationProvider";
import AssetProvider from "@/components/providers/AssetProvider";
import SoundProvider from "@/components/providers/SoundProvider";
import LeadModalProvider from "@/components/ui/LeadModalProvider";

import MagneticCursor from "@/components/ui/MagneticCursor";
import StickyCta from "@/components/ui/StickyCta";
import ExitIntent from "@/components/ui/ExitIntent";
import AnnouncementBar from "@/components/ui/AnnouncementBar";
import BuildMarker from "@/components/providers/BuildMarker";

const sans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

const display = Inter({
  subsets: ["latin"],
  variable: "--font-display",
  weight: ["500", "600", "700", "800", "900"],
  display: "swap",
});

const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL ?? BRAND.url,
  ),
  title: {
    default: `${BRAND.name} — ${BRAND.tagline}`,
    template: `%s · ${BRAND.name}`,
  },
  description: BRAND.supporting,
  applicationName: BRAND.name,
  alternates: {
    canonical: "/",
  },
  keywords: [
    "web development",
    "client portals",
    "Stripe checkout integration",
    "Next.js agency",
    "small business websites",
    "Resend automations",
    "remote web studio",
    "U.S. web developer",
  ],
  openGraph: {
    title: `${BRAND.name} — ${BRAND.tagline}`,
    description: BRAND.supporting,
    type: "website",
    siteName: BRAND.name,
    url: BRAND.url,
    locale: "en_US",
    // /opengraph-image is auto-generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: `${BRAND.name} — ${BRAND.tagline}`,
    description: BRAND.supporting,
    creator: "@weblogicdigital",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      // Single SVG covers every browser size. `sizes: "any"` tells browsers
      // not to bother requesting a 16/32 PNG fallback. The `?v=` is a
      // cache-buster — browsers are notoriously aggressive about caching
      // favicons across sessions; bumping this string forces a refetch
      // on the next visit after a redeploy.
      { url: "/icons/favicon.svg?v=2", type: "image/svg+xml", sizes: "any" },
    ],
    shortcut: "/icons/favicon.svg?v=2",
    apple: [
      // iOS Home Screen — same SVG. For pixel-perfect retina rendering
      // drop a 180×180 PNG at /icons/apple-touch-icon.png and Next will
      // auto-prefer it.
      { url: "/icons/favicon.svg?v=2" },
    ],
  },
};

export const viewport: Viewport = {
  themeColor: "#020410",
  width: "device-width",
  initialScale: 1,
  colorScheme: "dark",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Resolved at build time by Vercel — surfaced in the browser console so you
  // can confirm which deployment is being served.
  const commit =
    process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_SHA?.slice(0, 7) ??
    process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 7) ??
    null;
  const buildTime = new Date().toISOString();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${sans.variable} ${display.variable} ${mono.variable} bg-ink-0`}
    >
      <head>
        {/* Preload the brand logo — it's above-the-fold on every route,
            so the browser starts fetching it the moment HTML arrives, in
            parallel with everything else. Path is /brand/ (committed) not
            /uploads/ (gitignored) so production never 404s. */}
        <link
          rel="preload"
          as="image"
          href="/brand/logo.png"
          fetchPriority="high"
        />
      </head>
      <body className="bg-ink-0 text-bone antialiased" suppressHydrationWarning>
        <BuildMarker commit={commit} buildTime={buildTime} />
        <PersonalizationProvider>
          <AssetProvider>
            <SoundProvider>
              <LeadModalProvider>
                <SmoothScrollProvider>
                  <AnnouncementBar />
                  {children}
                  {/* Global UI — public site only, no admin chrome */}
                  <MagneticCursor />
                  <StickyCta />
                  <ExitIntent />
                </SmoothScrollProvider>
                {/* Vercel observability — Speed Insights captures Core Web Vitals
                    (LCP / INP / CLS) and Analytics captures pageviews. Both
                    no-op outside Vercel hosting, so they're safe in dev. */}
                <SpeedInsights />
                <Analytics />
              </LeadModalProvider>
            </SoundProvider>
          </AssetProvider>
        </PersonalizationProvider>

        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              name: BRAND.name,
              url: process.env.NEXT_PUBLIC_SITE_URL ?? BRAND.url,
              slogan: BRAND.tagline,
              description: BRAND.supporting,
              foundingDate: BRAND.established,
              email: BRAND.email,
              areaServed: { "@type": "Country", name: "United States" },
              contactPoint: {
                "@type": "ContactPoint",
                contactType: "sales",
                email: BRAND.email,
                availableLanguage: ["en"],
                areaServed: "US",
              },
            }),
          }}
        />
      </body>
    </html>
  );
}
